#22 > 7주차 과제 람다와 스트림 제출
SeungHeeNoh/study_well pull request #25
Opened 2022-12-01 13:52 UTC by testall0836

2022-12-02 05:57 UTC, SeungHeeNoh commented on kdk/람다와스트림.md
> +(int x, int b) -> a > b ? a : b
선언한 매개변수와 식에서 사용하는  변수가 일치하지 않아 에러가 발생할 것 같습니다~
확인 부탁드려요~

2022-12-05 00:51 UTC, SeungHeeNoh requested changes
첫 번째 문제풀이 다시 확인해주세요~ :)

2022-12-06 04:32 UTC, testall0836 commented on kdk/람다와스트림.md
> +(int x, int b) -> a > b ? a : b
전달해주신 내용 확인하여 수정하였습니다~

2022-12-06 04:41 UTC, SeungHeeNoh approved these changes
수정 확인했습니다~ 고생하셨습니다~

2022-12-06 13:39 UTC, merged