#36 > 9주차 과제 > 문제 풀기 완료
SeungHeeNoh/study_well pull request #49
Opened 2022-12-14 15:11 UTC by SeungHeeNoh

추가문제, 5, 6 문제 풀기 완료

#36

2022-12-16 07:51 UTC, QuanXiuzhi requested changes
코멘트 참고 부탁 드립니다~

2022-12-16 07:51 UTC, QuanXiuzhi commented on nsh/람다와 스트림-추가문제,5,6.md
> +System.out.println(test.accept(new StringBuffer(), "Hello!").toString());
오타가 있는 거 같네요 accept => apply

2022-12-16 07:51 UTC, QuanXiuzhi commented on nsh/람다와 스트림-추가문제,5,6.md
> +Supplier<NullPointerException> test = NullPointerException::new;
[참고] 의도한 것인지 모르겠으나, 제네릭이 NullPointerException일 경우 test.get() instanceof ArithmeticException은 에러코드가 됩니다.

2022-12-16 07:57 UTC, SeungHeeNoh commented on nsh/람다와 스트림-추가문제,5,6.md
> +Supplier<NullPointerException> test = NullPointerException::new;
제가 테스트하면서 이슈가 없었던 거 같은데, 아무래도 마지막 instaceof를 테스트 없이 추가한 거 같습니다.ㅠ
여기서는 반환되는 값이 정확하게 NullPointerException임을 명시하기 위해 제네릭타입이 NullPointerException로 선언하도록 하는 게 제 의도였습니다.

2022-12-16 08:05 UTC, SeungHeeNoh commented
@QuanXiuzhi 
12번에서 잘못된 메소드를 사용했던 부분 수정했습니다.

확인 부탁드립니다.
감사합니다.

2022-12-19 00:32 UTC, QuanXiuzhi approved these changes
고생하셨습니다~!!

2022-12-19 00:34 UTC, merged