#39 > 9주차 과제 > 문제 풀기 완료
SeungHeeNoh/study_well pull request #53
Opened 2022-12-20 01:02 UTC by hithae-hothae

2022-12-20 06:04 UTC, SeungHeeNoh requested changes
코멘트 달린 부분 확인 부탁드려요!
그 외에는 모두 이상 없습니다. 고생하셨습니다!

2022-12-20 06:04 UTC, SeungHeeNoh commented on daniel/9주차과제.md
> +Function<String, String> test = String::toUpperCase;
해당 함수도 동작하는 데에는 이슈가 없습니다! 다만, 제네릭을 1번만 선언하고 사용할 수 있는 함수형 인터페이스가 존재합니다. 해당 부분은 굳이 수정하실 필요는 없고 코멘트로 답변 부탁드려요!

2022-12-22 02:27 UTC, hithae-hothae commented on daniel/9주차과제.md
> +BiFunction<Integer,Integer,Integer> test = Integer::compare;
수정했습니다.

2022-12-22 02:27 UTC, hithae-hothae commented on daniel/9주차과제.md
> +Supplier test = NullPointerException::new;
수정했습니다.

2022-12-22 02:27 UTC, hithae-hothae commented on daniel/9주차과제.md
> +Supplier test = Math::random;
수정했습니다.

2022-12-22 13:16 UTC, hithae-hothae commented on daniel/9주차과제.md
> +Function<String, String> test = String::toUpperCase;
UnaryOperator<String> test = String::toUpperCase;
System.out.println(test.apply("hi"));

2022-12-23 00:12 UTC, SeungHeeNoh approved these changes
고생하셨습니다! main으로 merge 부탁드립니다.

2022-12-28 00:31 UTC, merged